#ifndef _FILESYSTEM_FAT_H
#define _FILESYSTEM_FAT_H

#define FAT_BPB_OFFSET_DISASSEMBLE		0x00
#define FAT_BPB_OFFSET_OEM_ID			0x03
#define FAT_BPB_OFFSET_SECT_BYTES		0x0B
#define FAT_BPB_OFFSET_CLUSTER_BYTES	0x0D
#define FAT_BPB_OFFSET_RESERVED			0x0E
#define FAT_BPB_OFFSET_FAT_COUNT		0x10
#define FAT_BPB_OFFSET_ROOTD_ENTRIES	0x11
#define FAT_BPB_OFFSET_LOGICAL_SECTS	0x13
#define FAT_BPB_OFFSET_

#endif
