#define COM1 0x3f8
#define COM2 0x2f8

#define SERIAL_OFFSET_DATA			0
#define SERIAL_OFFSET_DIV_LEAST		0
#define SERIAL_OFFSET_INT_ENABLE	1
#define SERIAL_OFFSET_DIV_MOST		1
#define SERIAL_OFFSET_INTERRUPT_ID	2
#define SERIAL_OFFSET_FIFO			2
#define SERIAL_OFFSET_LINE_CONTROL	3
#define SERIAL_OFFSET_MODEM_CONTROL	4
#define SERIAL_OFFSET_LINE_STATUS	5
#define SERIAL_OFFSET_MODEM_STATUS	6
#define SERIAL_OFFSET_SCRATCH		7