#include "krnlstatus.h"

KRNL_MAKE_STATUS(KRNL_STATUS_UNKNOWN,	0, VGA_COLOR_WHITE,			"?",		'?');
KRNL_MAKE_STATUS(KRNL_STATUS_OKAY,		1, VGA_COLOR_LIGHT_GREEN,	"OKAY",		'K');
KRNL_MAKE_STATUS(KRNL_STATUS_NOTE,		2, VGA_COLOR_LIGHT_BLUE,	"NOTE",		'N');
KRNL_MAKE_STATUS(KRNL_STATUS_WARNING,	3, VGA_COLOR_LIGHT_BROWN,	"WARN",		'W');
KRNL_MAKE_STATUS(KRNL_STATUS_FAIL,		4, VGA_COLOR_LIGHT_RED,		"FAIL",		'E');
KRNL_MAKE_STATUS(KRNL_STATUS_FATAL,		5, VGA_COLOR_LIGHT_RED,		"FATAL",	'F');
